Fix YQ syntax to parse .github/actions.yml
47degrees/.github pull request #76
Opened 2021-01-20 21:14 UTC by sloshy

I've noticed that the sbt-microsites build has been broken for about a month or so, and in trying to figure out why I found several different issues including how it was not loading files locally on my machine properly. After fixing that, I noticed that the build was failing for a different reason: jekyll was not installed. There is a CI precondition to install jekyll specifically for sbt-microsites, and it was failing with a syntax error:

<img width="638" alt="Screen Shot 2021-01-20 at 2 49 11 PM" src="https://user-images.githubusercontent.com/427237/105237642-024c9d80-5b32-11eb-9306-4f887fc28038.png">

This error is in the PR linked here: https://github.com/47degrees/sbt-microsites/pull/529

After looking into what was going on I found that the `yq` syntax was incorrect, or perhaps out of date, so I fixed it with a version that I've tested works on my machine.

2021-01-20 21:16 UTC, sloshy commented
@alejandrohdezma I've added you as a reviewer, because it looks like you were the one who added this script to begin with. I want to make sure that I am fixing it properly so that I do not inadvertently cause some downstream errors. Thanks in advance!

2021-01-21 06:05 UTC, alejandrohdezma commented
Thanks @sloshy! This seems to be because a new version of `yq` (`v4`) has been released which modified how the library operates.

2021-01-21 06:08 UTC, alejandrohdezma requested changes

2021-01-21 06:08 UTC, alejandrohdezma commented on workflows/ci.yml
> +        run: test -f .github/actions.yml && eval "$(yq -r .pre.ci .github/actions.yml)" || true
Taking a look at the [`v3 to v4`](https://mikefarah.gitbook.io/yq/upgrading-from-v3#reading-with-default-value) docs, we should use and "evaluate" expression and recover the default value:

```suggestion
        run: test -f .github/actions.yml && eval "$(yq e '.pre.ci // "true"' .github/actions.yml)" || true
```

2021-01-21 06:08 UTC, alejandrohdezma commented on workflows/ci.yml
> +        run: test -f .github/actions.yml && eval "$(yq -r .post.ci .github/actions.yml)" || true
Taking a look at the [`v3 to v4`](https://mikefarah.gitbook.io/yq/upgrading-from-v3#reading-with-default-value) docs, we should use and "evaluate" expression and recover the default value:

```suggestion
        run: test -f .github/actions.yml && eval "$(yq e '.post.ci // "true"' .github/actions.yml)" || true
```

2021-01-21 06:08 UTC, alejandrohdezma commented on workflows/docs.yml
> +        run: test -f .github/actions.yml && eval "$(yq -r .pre.docs .github/actions.yml)" || true
Taking a look at the [`v3 to v4`](https://mikefarah.gitbook.io/yq/upgrading-from-v3#reading-with-default-value) docs, we should use and "evaluate" expression and recover the default value:

```suggestion
        run: test -f .github/actions.yml && eval "$(yq e '.pre.docs // "true"' .github/actions.yml)" || true
```

2021-01-21 06:08 UTC, alejandrohdezma commented on workflows/docs.yml
> +        run: test -f .github/actions.yml && eval "$(yq -r .post.docs .github/actions.yml)" || true
Taking a look at the [`v3 to v4`](https://mikefarah.gitbook.io/yq/upgrading-from-v3#reading-with-default-value) docs, we should use and "evaluate" expression and recover the default value:

```suggestion
        run: test -f .github/actions.yml && eval "$(yq e '.post.docs // "true"' .github/actions.yml)" || true
```

2021-01-21 06:08 UTC, alejandrohdezma commented on workflows/release.yml
> +        run: test -f .github/actions.yml && eval "$(yq -r .pre.release .github/actions.yml)" || true
Taking a look at the [`v3 to v4`](https://mikefarah.gitbook.io/yq/upgrading-from-v3#reading-with-default-value) docs, we should use and "evaluate" expression and recover the default value:

```suggestion
        run: test -f .github/actions.yml && eval "$(yq e '.pre.release // "true"' .github/actions.yml)" || true
```

2021-01-21 06:08 UTC, alejandrohdezma commented
Also the `post.release` will also need fixing

2021-01-21 17:19 UTC, sloshy commented on workflows/ci.yml
> +        run: test -f .github/actions.yml && eval "$(yq -r .pre.ci .github/actions.yml)" || true
Fixed

2021-01-21 17:20 UTC, sloshy commented on workflows/ci.yml
> +        run: test -f .github/actions.yml && eval "$(yq -r .post.ci .github/actions.yml)" || true
Fixed

2021-01-21 17:20 UTC, sloshy commented on workflows/docs.yml
> +        run: test -f .github/actions.yml && eval "$(yq -r .pre.docs .github/actions.yml)" || true
Fixed

2021-01-21 17:20 UTC, sloshy commented on workflows/docs.yml
> +        run: test -f .github/actions.yml && eval "$(yq -r .post.docs .github/actions.yml)" || true
Fixed

2021-01-21 17:20 UTC, sloshy commented on workflows/release.yml
> +        run: test -f .github/actions.yml && eval "$(yq -r .pre.release .github/actions.yml)" || true
Fixed

2021-01-21 17:21 UTC, sloshy commented
@alejandrohdezma Just went through and applied your suggestions. I also made an interesting discovery: the version of `yq` on my local machine was in Python, not Go, the one that is being used here. They have a slight difference in their syntax (the Python one uses `-e` style instead of `e`). That is highly confusing. But, I was able to test locally that it works, so that is good. Thank you for reviewing and lmk if there is anything else that looks off.

2021-01-21 17:27 UTC, alejandrohdezma approved these changes
Everything looks good to me now :) Thanks!

2021-01-21 17:27 UTC, merged